name: actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check diff
        uses: docker://tfug/proofreading:latest
        with:
          args: ./bin/run tensorflow/docs master

      - name: Check all
        uses: docker://tfug/proofreading:latest
        with: 
          args: ./bin/run tensorflow/docs master all
